knp_paginator:
    default_options:
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
    template:
        pagination: 'paginator/paginator.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
